language: php
dist: bionic

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2

env:
  global:
    - COMPOSER_MEMORY_LIMIT=2G
    - BASE_URL="http://127.0.0.1:8080"
    - SCREENSHOTS_PATH="/tmp"
    # Todo: install Selenium.
    - WEBDRIVER_HOST="http://127.0.0.1:4444"

mysql:
  database: herbalstore
  username: root
  encoding: utf8

services:
  - mysql

install:
  - composer --verbose install

script:
  - vendor/bin/behat
